---
cloud_provider:
    type: cfcmd
    url: https://api.run.asv-pr.ice.predix.io
    org: predix-devops-hc
    space: training
    self_signed: true
    default_domain: run.asv-pr.ice.predix.io
artifact_store:
    type: artifactory
    url: https://devcloud.swcoe.ge.com/artifactory
hooks:
    init_hook: "./initHook.sh"
    application_hooks:
        specific:
           - app: tkk-comp-app-1
             pre_publish: "./tkk-comp-1-pre-publish.sh"

