cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n api1
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n api2
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn1
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn2
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn3
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn4
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn5
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn6
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn7
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn8
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn9
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn10
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn11
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn12
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn13
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn14
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn15
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn16
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn17
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn18
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn19
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn20
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn21
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn22
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn23
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn24
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn25
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn26
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn27
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn28
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn29
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn30
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn31
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn32
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn33
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn34
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn35
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn36
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn37
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn38
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn39
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn40
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn41
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn42
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn43
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn44
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn45
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn46
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn47
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn48
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn49
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn50
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn51
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn52
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn53
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn54
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn55
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn56
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn57
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn58
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn59
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn60
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn61
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn62
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn63
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn64
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn65
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn66
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn67
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn68
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn69
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn70
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn71
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn72
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn73
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn74
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn75
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn76
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn77
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn78
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn79
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn80
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn81
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn82
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn83
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn84
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn85
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn86
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn87
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn88
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn89
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn90
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn91
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn92
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn93
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn94
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn95
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn96
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn97
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn98
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn99
cf map-route ci-comp-app-1-test1 run.asv-pr.ice.predix.io -n dyn100
